/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CatalogueRequest {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
}
export interface ContentBlock { 'key' : string, 'value' : string }
export interface Inquiry {
  'country' : string,
  'inquiryType' : InquiryType,
  'name' : string,
  'isRead' : boolean,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type InquiryType = { 'catalogue' : null } |
  { 'general' : null } |
  { 'wholesale' : null };
export interface Product {
  'id' : bigint,
  'moq' : string,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, string, Array<string>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getAllCatalogueRequests' : ActorMethod<[], Array<CatalogueRequest>>,
  'getAllContentBlocks' : ActorMethod<[], Array<ContentBlock>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentBlock' : ActorMethod<[string], [] | [string]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setContentBlock' : ActorMethod<[string, string], undefined>,
  'submitCatalogueRequest' : ActorMethod<[string, string], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string, string, InquiryType],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, string, Array<string>],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];